CREATE TYPE "public"."schemaVersionStatus" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
CREATE TABLE "schemaVersions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schemaVersions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid() NOT NULL,
	"content" jsonb NOT NULL,
	"status" "schemaVersionStatus" DEFAULT 'draft' NOT NULL,
	"schemaId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	"orgId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schemas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schemas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" uuid DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(255) NOT NULL,
	"orgId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "schemaVersions" ADD CONSTRAINT "schemaVersions_schemaId_schemas_id_fk" FOREIGN KEY ("schemaId") REFERENCES "public"."schemas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schemaVersions" ADD CONSTRAINT "schemaVersions_orgId_orgs_id_fk" FOREIGN KEY ("orgId") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schemas" ADD CONSTRAINT "schemas_orgId_orgs_id_fk" FOREIGN KEY ("orgId") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uniqueTitlePerOrg" ON "schemas" USING btree ("orgId","title");